apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: coc
resources:
  - namespace.yaml
  - configmaps.yaml
  - services.yaml
  - deployments.yaml
  - pvc.yaml
  - ingress.yaml
  - middlewares.yaml
